package com.example.myapplication.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val CardBackground = Color(0xFFF5F9FA)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)


val primaryLightHighContrast = Color(0xFF003233)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF005253)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0B3132)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2C4F4F)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3C1C5A)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF5A3B79)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF6FAF9)
val onBackgroundLightHighContrast = Color(0xFF181C1C)
val surfaceLightHighContrast = Color(0xFFF6FAF9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFD9E5E4)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF232E2E)
val outlineVariantLightHighContrast = Color(0xFF404B4B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2C3131)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF72D6D7)
val surfaceDimLightHighContrast = Color(0xFFB5BAB9)
val surfaceBrightLightHighContrast = Color(0xFFF6FAF9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEDF2F1)
val surfaceContainerLightHighContrast = Color(0xFFDFE3E3)
val surfaceContainerHighLightHighContrast = Color(0xFFD1D5D5)
val surfaceContainerHighestLightHighContrast = Color(0xFFC3C7C7)



val primaryDarkHighContrast = Color(0xFFA9FFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF6DD2D3)
val onPrimaryContainerDarkHighContrast = Color(0xFF000E0E)
val secondaryDarkHighContrast = Color(0xFFD1F7F7)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA5CAC9)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0E)
val tertiaryDarkHighContrast = Color(0xFFF9EBFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFD9B3FC)
val onTertiaryContainerDarkHighContrast = Color(0xFF15002B)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0F1414)
val onBackgroundDarkHighContrast = Color(0xFFDFE3E3)
val surfaceDarkHighContrast = Color(0xFF0F1414)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3D4949)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE6F2F2)
val outlineVariantDarkHighContrast = Color(0xFFB9C5C4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDFE3E3)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF005151)
val surfaceDimDarkHighContrast = Color(0xFF0F1414)
val surfaceBrightDarkHighContrast = Color(0xFF4C5151)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C2020)
val surfaceContainerDarkHighContrast = Color(0xFF2C3131)
val surfaceContainerHighDarkHighContrast = Color(0xFF373C3C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF434847)

